services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/code
      - ./tokens/.cloud_creds/gcp:/cloud_creds/gcp
      - ./certs/domain_dir/domain.key:/certs/domain.key
    environment:
      FLASK_DEBUG: "false"
